### ISSUE TITLE
Add *.booru.org support

### ISSUE THREAD

**Issue by AtoraSuunva** [AtoraSuunva/Booru-Discord#11]
Some apis work
http://size.booru.org/index.php?page=dapi&s=post&q=index&tags=
others don't

I need to look into this

Also I need to figure out how to invoke it 
`=b.[shortName] [tags]`?
`=b.size building`?

**Comment by austinhuang0131** [comment]
Most sites don't have it. I know that `furry.booru.org` also has it, but I think there's no one else has it.

**Comment by AtoraSuunva** [comment]
Probably not going to do it actually
Anyways this issue should be moved to https://github.com/AtlasTheBot/booru
