### ISSUE TITLE
blacklisting all sites broken

### ISSUE THREAD

**Issue by JayEff87** [AtoraSuunva/Booru-Discord#20]
While whitelisting all sites works fine via the command ```b!wl sites all```, blacklisting does not. The following commands all result in the same error:
```
b!bl sites all
b!bl site all
b!blacklist site all
b!blacklist sites all
```
The error is: "Failed to blacklist undefined: undefined" followed by an unchanged blacklisted sites list.

**Comment by AtoraSuunva** [comment]
Ah, that's because I forgot a spread operator lol

Changes are live on BooruBot, I'll push to git when I can
