### ISSUE TITLE
Add setting that prohibits non-moderators from using deletThis emoji

### ISSUE THREAD

**Issue by PatPeter** [AtoraSuunva/Booru-Discord#24]
For very large Discords with a lot of members in a #nsfw channel, it would be great to prohibit ordinary users from deleting images, especially to stop trolls who try to delete all images of a certain category.

**Comment by AtoraSuunva** [comment]
"Fixed" in eee07f057779c509356836e6c67c81ad212d1913

That commit changes the "deletThis" reaction to only work for either the user who originally called the search, or members with "Manage Messages" permissions.

**Comment by PatPeter** [comment]
Thank you very much for the quick reply and for fixing this!
