### ISSUE TITLE
Add setting to disable arrow_forward functionality

### ISSUE THREAD

**Issue by PatPeter** [AtoraSuunva/Booru-Discord#25]
I hate when a group of people are all memeing or spamming the #nsfw channel and people decide to click the arrow_forward button before someone's had a chance to either look at an image someone's talking about, or open it in their browser so that they have a reference to it. It would be great if this functionality could be disabled with a setting.

**Comment by AtoraSuunva** [comment]
Added in eee07f057779c509356836e6c67c81ad212d1913

Use `disableNextImage` to disable it.

```ascidoc
disableNextImage
================
Type----:: boolean
Default-:: false
Current-:: false

Disables the "next image" arrow reaction
```

**Comment by PatPeter** [comment]
Thank you so much for the functionality _and_ for the quick response!
