### ISSUE TITLE
"Found no images anywhere..." for every b!random query

### ISSUE THREAD

**Issue by PatPeter** [AtoraSuunva/Booru-Discord#27]
Sorry for the third bug request, but since the new update a few hours ago the `b!random` query no longer works and says "Found no images anywhere...".

**Comment by AtoraSuunva** [comment]
Can reproduce it, I changed the logic for searching slightly with the last update so it's not 100% unexpected.

I'm busy, but I'll try and fix it ASAP (most likely on Friday though)

**Comment by PatPeter** [comment]
No problem! Thank you for your quick replies.

**Comment by AtoraSuunva** [comment]
Fixed

Changed how search worked and since random search uses that it broke. Changes are live now

**Comment by PatPeter** [comment]
Awesome! Just tested it and @everyone'd my Booru Bot channel >:) Thank you for fixing it.
