### ISSUE TITLE
request

### ISSUE THREAD

**Issue by kille250** [AtoraSuunva/Booru-Discord#29]
Wanted to request a site!

https://solidwolfe.xyz

This site is using danbooru v2.
Thank you in advance, also if you don't want to add it c:

**Comment by PatPeter** [comment]
You should change the title of your request to, "Add new site Solidwolfe.xyz" so that the author knows what your request is before clicking the issue.

**Comment by AtoraSuunva** [comment]
This issue would be better suited for https://github.com/AtlasTheBot/booru since that's the library used to search boorus

Although I've been planning on a way to add in your own boorus, it requires work to be done in booru before it can be added to the bot
