### ISSUE TITLE
Blacklist not working?

### ISSUE THREAD

**Issue by TheEclipsedLock** [AtoraSuunva/Booru-Discord#33]
Hello! I've been trying to blacklist a lot of tags, using the following command:
b!bl tags <tag>
b!bl sites <site>

But the bot does not seem to be able to accept those. When doing b!bl <tag>, it mentions to say if it is a tag or a site plurally. Adding it in does not seem to go so well, with other commands working as intended. Could it be an issue with the bot?

Nevermind, it seemed to work now.... but thanks for offering bot services!

**Comment by AtoraSuunva** [comment]
That was an issue on my end, I accidentally caused a naming conflict (So it would error).

I just fixed it live right as you submitted the issue, funny timing!
