### ISSUE TITLE
Lolibooru.moe search is not working

### ISSUE THREAD

**Issue by VectorGames055** [AtoraSuunva/Booru-Discord#36]
When I use the b!s lb <tag> command it says "That is not a valid site to search"

**Comment by AtoraSuunva** [comment]
Lolibooru support was removed in the [booru package](https://github.com/AtlasTheBot/booru/commit/08ff480121f0c51503a8464db5c7bff7514b8675) BooruBot uses to search.

Loli/shota/cub art is also banned by Discord's [community guidelines](https://discord.com/guidelines) so I'm even less interested in re-adding support.
