### ISSUE TITLE
where is the config_example.json

### ISSUE THREAD

**Issue by 0d1nAndl0k1** [AtoraSuunva/Booru-Discord#44]
Hello, i am looking at how to make this but can not find the config_example.json file please help me

**Comment by AtoraSuunva** [comment]
Oh it looks like I ended up removing it some commits ago, I readded it back here https://github.com/AtlasTheBot/Booru-Discord/blob/master/config_example.json

I've also updated the selfhosting section https://github.com/AtlasTheBot/Booru-Discord#selfhosting
