### ISSUE TITLE
Booru bot not working when trying to trigger the bot

### ISSUE THREAD

**Issue by tsRickster** [AtoraSuunva/Booru-Discord#48]
When i use booru gel tag it doesn’t trigger the bot anymore, it was just working not too long ago Channel is 18+ and the bot has admin priv. / commands work but triggering the bot in chat just doesn’t work. There aren’t any blacklists and min score is 0. It was just working a while ago and now it just stopped. Please help.

**Comment by tsRickster** [comment]
figured it out guess i didn’t see it changed to /search thanks :D

**Comment by AtoraSuunva** [comment]
Yup, the bot changed to just use / commands (I don't have access to message content anymore so I can't do chat commands)

You can read the changes here https://github.com/AtoraSuunva/Booru-Discord/releases/tag/v4.0.0
