### ISSUE TITLE
Non-working blacklist

### ISSUE THREAD

**Issue by DARTYTRAD** [AtoraSuunva/Booru-Discord#52]
All commands work except those where there is a command "/blacklist"

**Comment by AtoraSuunva** [comment]
![SmartSelect_20230914_145235_Discord](https://github.com/AtoraSuunva/BooruBot/assets/15206032/832cc773-ad3d-4caa-8fc2-932119f6d005)

It's working fine for me, are you getting an error message or does the bot just not respond?

**Comment by DARTYTRAD** [comment]
After it is written that "BooruBot is thinking" after a while, such an inscription appears, which is located above
![Screenshot_20230914_224257_com discord_1](https://github.com/AtoraSuunva/BooruBot/assets/145057256/1b719588-3cf2-4162-8232-126d478333b3)

**Comment by DARTYTRAD** [comment]
Could it be that the error was issued due to the fact that I wrote too many tags, or wrote them incorrectly?

**Comment by AtoraSuunva** [comment]
Maybe? If you have way too many tags the message might just be so long that Discord doesn't let the bot send the reply.

I added better error logging and did a fix in case of too many tags, can you try again and see if it works now?

**Comment by DARTYTRAD** [comment]
Thank you very much! Everything is working now. It's just that for me it's the best bot because of its ease of use and without unnecessary functions, so I wanted it to work without interruptions.
I apologize for not telling you right away about the cause of the error and the time spent
